export const servicesData = {
  assessment: {
    title: "IAM Assessment",
    tagline: "Know your identity security posture — honestly",
    heroDesc:
      "We help organisations understand their true security posture across identity, access management, SWIFT CSP controls, compliance frameworks and operating models — with structured findings and a clear path to improvement.",
    icon: "BarChart3",
    targetClient: "Any organisation that wants to understand its IAM risk before committing to a programme — or that needs a credible baseline for board reporting.",
    whatWeDo: [
      "Workshop-based data gathering across five IAM domains",
      "Scoring against Infosec K2K's maturity framework",
      "Gap analysis with risk-rated findings",
      "Prioritised recommendations aligned to your budget and risk tolerance",
      "Executive summary and detailed technical report",
      "SWIFT Customer Security Programme (CSP) readiness and gap assessments",
      "Compliance maturity reviews against ISO 27001, DORA, FCA and Cyber Essentials+",
      "Operating model reviews for security and identity functions",
    ],
    howWeDeliver: [
      "Week 1–2: Stakeholder interviews and evidence collection",
      "Week 2–3: Analysis and scoring",
      "Week 3–4: Findings review and report delivery",
    ],
    caseStudy: {
      result: "A UK financial services firm discovered three critical gaps in their privileged access controls within two weeks. The assessment report directly informed a £2M IAM programme.",
      org: "UK Financial Services Group",
    },
  },
  roadmap: {
    title: "Roadmap & Strategy",
    tagline: "A prioritised, costed path to target maturity",
    heroDesc:
      "Turn your assessment findings — or a known set of requirements — into a practical, board-ready programme plan. We build roadmaps that survive contact with budget reality.",
    icon: "TrendingUp",
    targetClient:
      "Organisations that have completed an assessment, or that already know their gaps but need a structured plan for addressing them.",
    whatWeDo: [
      "Current state analysis and gap prioritisation",
      "Target state definition aligned to compliance requirements",
      "12–24 month programme sequencing",
      "Quick win identification (30/60/90 day actions)",
      "Resource, tooling and budget modelling",
      "Stakeholder-ready presentation",
    ],
    howWeDeliver: [
      "Week 1–2: Requirements and constraint discovery",
      "Week 2–4: Roadmap drafting and scenario modelling",
      "Week 4–6: Review, iteration and final delivery",
    ],
    caseStudy: {
      result: "A central government agency used our roadmap to secure board approval for a three-year IAM transformation. The 90-day quick wins were in flight within weeks of delivery.",
      org: "Central Government Agency",
    },
  },
  implementation: {
    title: "Implementation & Optimisation",
    tagline: "Hands-on delivery — not just slide decks",
    heroDesc:
      "From PAM deployments and MFA rollouts to IGA platform implementation, we deliver the work. Every project runs through our client portal so you always know where things stand.",
    icon: "Shield",
    targetClient:
      "Organisations with a defined programme who need experienced delivery resource, or that have IAM tooling in place that isn't delivering its full potential.",
    whatWeDo: [
      "Scoped delivery with named consultants",
      "Platform implementation and configuration",
      "Integration with existing directory and application estate",
      "Policy and process development",
      "Full documentation and knowledge transfer",
      "Post-go-live support and handover",
    ],
    howWeDeliver: [
      "Project kick-off: scope, access, delivery plan agreed",
      "Delivery tracked in your client portal throughout",
      "Regular progress calls and milestone sign-off",
      "Formal handover with runbooks and training",
    ],
    caseStudy: {
      result: "We delivered a full PAM programme for an enterprise retailer in six months, covering 800 privileged accounts and integrating with their existing SIEM.",
      org: "UK Enterprise Retailer",
    },
  },
  managed: {
    title: "Managed Identity Services",
    tagline: "Ongoing identity security without the overhead",
    heroDesc:
      "Identity security isn't a project — it's a continuous discipline. Our managed service gives you expert coverage across monitoring, access reviews, incident response and periodic assurance.",
    icon: "ShieldAlert",
    targetClient:
      "Organisations that have completed implementation and want to maintain and evolve their IAM posture without building a large in-house function.",
    whatWeDo: [
      "Continuous identity threat monitoring",
      "Regular access certification and joiner/mover/leaver reviews",
      "Privileged access health checks",
      "Quarterly posture reviews with your team",
      "Incident response support for identity-related events",
      "Portal dashboard with real-time service health",
    ],
    howWeDeliver: [
      "Onboarding: environment integration and baseline review",
      "Monthly: operational reviews and threat monitoring",
      "Quarterly: formal health review and roadmap update",
      "On-demand: incident response and advisory support",
    ],
    caseStudy: {
      result: "A regulated financial services firm moved to our managed service after implementation, reducing access review cycle time by 70% and achieving continuous compliance monitoring.",
      org: "Regulated Financial Services Firm",
    },
  },
  "tooling-strategy": {
    title: "Tooling Strategy & Support",
    tagline: "Vendor-agnostic. Outcome-led. Built around your architecture.",
    heroDesc: "We help organisations cut through vendor noise to select, implement and optimise the right identity and security tooling — without being tied to any single platform.",
    icon: "Wrench",
    targetClient: "Organisations evaluating or optimising identity security tooling",
    whatWeDo: [
      "Current tool estate review and capability gap analysis",
      "Vendor-neutral selection support across PAM, IGA, IAM, MFA and SIEM",
      "Architecture design and integration planning",
      "Security roadmap development aligned to budget and risk tolerance",
      "Implementation planning and delivery oversight",
      "Tool optimisation and configuration review for existing deployments",
    ],
    howWeDeliver: [
      "Discovery workshop with architecture and security stakeholders",
      "Current state capability assessment against target architecture",
      "Vendor shortlist with scored evaluation criteria",
      "Integration architecture blueprint",
      "Phased implementation roadmap with indicative costs",
      "Ongoing advisory retainer available post-delivery",
    ],
    caseStudy: { result: "Selected and implemented a PAM platform across 3,000 endpoints in 90 days", org: "Global Insurance Group" },
    category: "Advisory",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "Cyber Essentials+"],
    relatedServices: ["assessment", "managed", "assurance"],
    badge: null,
  },
  assurance: {
    title: "Assurance Services",
    tagline: "Evidence-led. Audit-ready. Board-presentable.",
    heroDesc: "We support organisations in building, evidencing and presenting robust security and compliance postures — from SWIFT CSP readiness to ISO 27001 and beyond.",
    icon: "ClipboardCheck",
    targetClient: "Regulated organisations requiring compliance assurance and evidence packs",
    whatWeDo: [
      "Security control framework reviews (ISO 27001, DORA, FCA, SWIFT CSP, Cyber Essentials+)",
      "SWIFT Customer Security Programme (CSP) readiness assessments and gap reviews",
      "Evidence collection planning and tracking",
      "Control mapping and gap analysis",
      "Assurance pack creation for auditors, regulators and boards",
      "Remediation prioritisation and tracking",
    ],
    howWeDeliver: [
      "Scoping session to agree framework scope and timelines",
      "Control inventory and current evidence review",
      "Gap register with risk-ranked findings",
      "Evidence collection tracker and owner assignment",
      "Draft assurance pack with narrative and control evidence",
      "Final board or auditor-ready output with executive summary",
    ],
    caseStudy: { result: "Achieved SWIFT CSP attestation and ISO 27001 certification within one programme", org: "Tier 2 UK Bank" },
    category: "Assurance",
    complianceRelevance: ["SWIFT CSP", "ISO 27001", "DORA", "FCA", "Cyber Essentials+", "GDPR"],
    relatedServices: ["assessment", "tooling-strategy", "offensive-security"],
    badge: null,
  },
  "offensive-security": {
    title: "Offensive Security",
    tagline: "Find your weaknesses before attackers do.",
    heroDesc: "Our offensive security practice delivers structured penetration testing, vulnerability assessments and ongoing vulnerability management — giving you the evidence to fix, prioritise and report with confidence.",
    icon: "Crosshair",
    targetClient: "Organisations seeking to validate their security controls through structured testing",
    whatWeDo: [
      "Infrastructure and web application penetration testing",
      "Internal and external network vulnerability assessments",
      "Identity and Active Directory attack path analysis",
      "Red team and assumed breach exercises",
      "Remediation planning and retesting",
      "Ongoing vulnerability management programmes",
    ],
    howWeDeliver: [
      "Scoping workshop to define targets, rules of engagement and timelines",
      "Structured testing using CREST-aligned methodology",
      "Real-time findings triage during engagement",
      "Full technical report with severity-rated findings",
      "Remediation guidance and prioritisation roadmap",
      "Retest engagement to validate fixes and update report",
    ],
    caseStudy: { result: "Identified 14 critical identity attack paths in an Active Directory estate of 40,000 accounts", org: "Global Manufacturing Group" },
    category: "Technical",
    complianceRelevance: ["ISO 27001", "Cyber Essentials+", "DORA", "NIS2", "PCI DSS"],
    relatedServices: ["assessment", "assurance", "managed"],
    badge: null,
  },
};
