export const servicesData = {
  assessment: {
    title: "IAM Assessment",
    tagline: "Know your identity security posture — honestly",
    heroDesc:
      "We help organisations understand their true security posture across identity, access management, SWIFT CSP controls, compliance frameworks and operating models — with structured findings and a clear path to improvement.",
    icon: "BarChart3",
    targetClient: "Any organisation that wants to understand its IAM risk before committing to a programme — or that needs a credible baseline for board reporting.",
    whatWeDo: [
      "Workshop-based data gathering across five IAM domains",
      "Scoring against Infosec K2K's maturity framework",
      "Gap analysis with risk-rated findings",
      "Prioritised recommendations aligned to your budget and risk tolerance",
      "Executive summary and detailed technical report",
      "SWIFT Customer Security Programme (CSP) readiness and gap assessments",
      "Compliance maturity reviews against ISO 27001, DORA, FCA and Cyber Essentials+",
      "Operating model reviews for security and identity functions",
    ],
    howWeDeliver: [
      "Week 1–2: Stakeholder interviews and evidence collection",
      "Week 2–3: Analysis and scoring",
      "Week 3–4: Findings review and report delivery",
    ],
    caseStudy: {
      result: "A UK financial services firm discovered three critical gaps in their privileged access controls within two weeks. The assessment report directly informed a £2M IAM programme.",
      org: "UK Financial Services Group",
    },
    category: "Identity Security",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "Cyber Essentials+", "SWIFT CSP", "NIS2"],
    relatedServices: ["roadmap", "implementation", "assurance"],
  },
  roadmap: {
    title: "Roadmap & Strategy",
    tagline: "A prioritised, costed path to target maturity",
    heroDesc:
      "Turn your assessment findings — or a known set of requirements — into a practical, board-ready programme plan. We build roadmaps that survive contact with budget reality.",
    icon: "TrendingUp",
    targetClient:
      "Organisations that have completed an assessment, or that already know their gaps but need a structured plan for addressing them.",
    whatWeDo: [
      "Current state analysis and gap prioritisation",
      "Target state definition aligned to compliance requirements",
      "12–24 month programme sequencing",
      "Quick win identification (30/60/90 day actions)",
      "Resource, tooling and budget modelling",
      "Stakeholder-ready presentation",
    ],
    howWeDeliver: [
      "Week 1–2: Requirements and constraint discovery",
      "Week 2–4: Roadmap drafting and scenario modelling",
      "Week 4–6: Review, iteration and final delivery",
    ],
    caseStudy: {
      result: "A central government agency used our roadmap to secure board approval for a three-year IAM transformation. The 90-day quick wins were in flight within weeks of delivery.",
      org: "Central Government Agency",
    },
    category: "Identity Security",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "NIS2"],
    relatedServices: ["assessment", "implementation", "managed"],
  },
  implementation: {
    title: "Implementation & Optimisation",
    tagline: "Hands-on delivery — not just slide decks",
    heroDesc:
      "From PAM deployments and MFA rollouts to IGA platform implementation, we deliver the work. Every project runs through our client portal so you always know where things stand.",
    icon: "Shield",
    targetClient:
      "Organisations with a defined programme who need experienced delivery resource, or that have IAM tooling in place that isn't delivering its full potential.",
    whatWeDo: [
      "Scoped delivery with named consultants",
      "Platform implementation and configuration",
      "Integration with existing directory and application estate",
      "Policy and process development",
      "Full documentation and knowledge transfer",
      "Post-go-live support and handover",
      "Cyolo zero-trust connectivity deployment — identity-based secure remote access implementation for OT, third-party and legacy application environments",
    ],
    howWeDeliver: [
      "Project kick-off: scope, access, delivery plan agreed",
      "Delivery tracked in your client portal throughout",
      "Regular progress calls and milestone sign-off",
      "Formal handover with runbooks and training",
    ],
    caseStudy: {
      result: "We delivered a full PAM programme for an enterprise retailer in six months, covering 800 privileged accounts and integrating with their existing SIEM.",
      org: "UK Enterprise Retailer",
    },
    category: "Identity Security",
    complianceRelevance: ["ISO 27001", "DORA", "FCA"],
    relatedServices: ["managed", "tooling-strategy", "assessment"],
  },
  managed: {
    title: "Managed Identity Services",
    tagline: "Ongoing identity security without the overhead",
    heroDesc:
      "Identity security isn't a project — it's a continuous discipline. Our managed service gives you expert coverage across monitoring, access reviews, incident response and periodic assurance.",
    icon: "ShieldAlert",
    targetClient:
      "Organisations that have completed implementation and want to maintain and evolve their IAM posture without building a large in-house function.",
    whatWeDo: [
      "Continuous identity threat monitoring",
      "Regular access certification and joiner/mover/leaver reviews",
      "Privileged access health checks",
      "Quarterly posture reviews with your team",
      "Incident response support for identity-related events",
      "Portal dashboard with real-time service health",
    ],
    howWeDeliver: [
      "Onboarding: environment integration and baseline review",
      "Monthly: operational reviews and threat monitoring",
      "Quarterly: formal health review and roadmap update",
      "On-demand: incident response and advisory support",
    ],
    caseStudy: {
      result: "A regulated financial services firm moved to our managed service after implementation, reducing access review cycle time by 70% and achieving continuous compliance monitoring.",
      org: "Regulated Financial Services Firm",
    },
    category: "Identity Security",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "UK GDPR"],
    relatedServices: ["implementation", "managed-detection", "technical-resources"],
  },
  "tooling-strategy": {
    title: "Tooling Strategy & Support",
    tagline: "Vendor-agnostic. Outcome-led. Built around your architecture.",
    heroDesc: "We help organisations cut through vendor noise to select, implement and optimise the right identity and security tooling — without being tied to any single platform.",
    icon: "Wrench",
    targetClient: "Organisations evaluating or optimising identity security tooling",
    whatWeDo: [
      "Current tool estate review and capability gap analysis",
      "Vendor-neutral selection support across PAM, IGA, IAM, MFA and SIEM",
      "Architecture design and integration planning",
      "Security roadmap development aligned to budget and risk tolerance",
      "Implementation planning and delivery oversight",
      "Tool optimisation and configuration review for existing deployments",
      "WSO2 Identity Server — open-source IAM platform design, implementation and integration for organisations requiring a flexible, self-hosted identity platform",
    ],
    howWeDeliver: [
      "Discovery workshop with architecture and security stakeholders",
      "Current state capability assessment against target architecture",
      "Vendor shortlist with scored evaluation criteria",
      "Integration architecture blueprint",
      "Phased implementation roadmap with indicative costs",
      "Ongoing advisory retainer available post-delivery",
    ],
    caseStudy: { result: "Selected and implemented a PAM platform across 3,000 endpoints in 90 days", org: "Global Insurance Group" },
    category: "Identity Security",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "Cyber Essentials+"],
    relatedServices: ["assessment", "managed", "assurance"],
    badge: null,
  },
  assurance: {
    title: "Assurance Services",
    tagline: "Evidence-led. Audit-ready. Board-presentable.",
    heroDesc: "We support organisations in building, evidencing and presenting robust security and compliance postures — from SWIFT CSP readiness to ISO 27001 and beyond.",
    icon: "ClipboardCheck",
    targetClient: "Regulated organisations requiring compliance assurance and evidence packs",
    whatWeDo: [
      "Security control framework reviews (ISO 27001, DORA, FCA, SWIFT CSP, Cyber Essentials+)",
      "SWIFT Customer Security Programme (CSP) readiness assessments and gap reviews",
      "Evidence collection planning and tracking",
      "Control mapping and gap analysis",
      "Assurance pack creation for auditors, regulators and boards",
      "Remediation prioritisation and tracking",
    ],
    howWeDeliver: [
      "Scoping session to agree framework scope and timelines",
      "Control inventory and current evidence review",
      "Gap register with risk-ranked findings",
      "Evidence collection tracker and owner assignment",
      "Draft assurance pack with narrative and control evidence",
      "Final board or auditor-ready output with executive summary",
    ],
    caseStudy: { result: "Achieved SWIFT CSP attestation and ISO 27001 certification within one programme", org: "Tier 2 UK Bank" },
    category: "Assurance",
    complianceRelevance: ["SWIFT CSP", "ISO 27001", "DORA", "FCA", "Cyber Essentials+", "GDPR"],
    relatedServices: ["assessment", "tooling-strategy", "offensive-security"],
    badge: null,
  },
  "offensive-security": {
    title: "Offensive Security",
    tagline: "Find your weaknesses before attackers do.",
    heroDesc: "Our offensive security practice delivers structured penetration testing, vulnerability assessments and ongoing vulnerability management — giving you the evidence to fix, prioritise and report with confidence.",
    icon: "Crosshair",
    targetClient: "Organisations seeking to validate their security controls through structured testing",
    whatWeDo: [
      "Infrastructure and web application penetration testing",
      "Internal and external network vulnerability assessments",
      "Identity and Active Directory attack path analysis",
      "Red team and assumed breach exercises",
      "Remediation planning and retesting",
      "Ongoing vulnerability management programmes",
      "Breach and attack simulation via Picus Security — continuous validation of security controls against real-world attack scenarios",
      "Continuous vulnerability management powered by Qualys — authenticated scanning, prioritisation and patch tracking across your estate",
    ],
    howWeDeliver: [
      "Scoping workshop to define targets, rules of engagement and timelines",
      "Structured testing using CREST-aligned methodology",
      "Real-time findings triage during engagement",
      "Full technical report with severity-rated findings",
      "Remediation guidance and prioritisation roadmap",
      "Retest engagement to validate fixes and update report",
    ],
    caseStudy: { result: "Identified 14 critical identity attack paths in an Active Directory estate of 40,000 accounts", org: "Global Manufacturing Group" },
    category: "Detection & Intelligence",
    complianceRelevance: ["ISO 27001", "Cyber Essentials+", "DORA", "NIS2", "PCI DSS"],
    relatedServices: ["assessment", "assurance", "managed"],
    badge: "Powered by Picus & Qualys",
  },
  "managed-detection": {
    title: "Managed Detection & Response",
    tagline: "24/7 threat detection powered by LevelBlue / AlienVault. Built for UK organisations without an in-house SOC.",
    heroDesc:
      "Infosec K2K Managed Detection — powered by LevelBlue / AlienVault — delivers continuous threat monitoring, correlation and response across your endpoints, network and cloud environments. We combine AlienVault's USM Anywhere platform with our UK-based analyst team to give you enterprise-grade detection at a fraction of the cost of building it yourself.",
    icon: "Radio",
    targetClient:
      "UK organisations — particularly in financial services, healthcare and critical infrastructure — that lack an in-house Security Operations Centre but face increasing regulatory pressure to demonstrate continuous threat monitoring and incident response capability. Ideal for organisations that have completed a cyber risk or IAM assessment and identified detection coverage as a priority gap.",
    whatWeDo: [
      "24/7 threat monitoring across endpoints, network, cloud and identity layers via USM Anywhere",
      "SIEM correlation and alert triage by our UK-based analyst team",
      "Threat intelligence integration including AlienVault OTX feeds and DomainTools signals",
      "Incident response playbooks and escalation procedures tailored to your environment",
      "Monthly threat reporting and quarterly detection coverage reviews",
      "Integration with existing EDR, firewall and identity tooling",
      "Regulatory-aligned logging and retention to support DORA, FCA and ISO 27001 requirements",
      "Onboarding including asset discovery, baseline profiling and detection rule tuning",
    ],
    howWeDeliver: [
      "Week 1–2: Onboarding — environment scoping, log source integration and baseline profiling",
      "Week 2–4: Detection tuning — rule customisation, false-positive reduction and escalation path setup",
      "Month 1 onwards: Continuous monitoring with monthly reporting and analyst handover notes",
      "Quarterly: Formal detection coverage review, rule update cycle and roadmap planning",
      "On-demand: Incident response support and threat hunting on request",
    ],
    caseStudy: {
      result:
        "A mid-market UK financial services firm without an in-house SOC achieved continuous monitoring across 1,200 endpoints within six weeks of onboarding. Three genuine threats were identified and contained in the first 90 days, including one lateral movement attempt originating from a compromised service account.",
      org: "Mid-Market UK Financial Services Firm",
    },
    category: "Detection & Intelligence",
    complianceRelevance: ["DORA", "FCA", "ISO 27001", "NIS2", "Cyber Essentials+"],
    relatedServices: ["assessment", "domain-intelligence", "offensive-security"],
    badge: "Powered by LevelBlue",
  },
  "domain-intelligence": {
    title: "Domain Intelligence & OSINT",
    tagline: "Continuous external exposure monitoring powered by DomainTools. Know what attackers know about you.",
    heroDesc:
      "Infosec K2K Domain Intelligence — powered by DomainTools — gives your organisation continuous visibility of its external attack surface: leaked credentials, domain infrastructure, subdomain footprint, brand exposure and threat actor activity targeting your sector. We combine DomainTools' enterprise-grade data with our analyst team to deliver actionable intelligence, not raw data.",
    icon: "Globe",
    targetClient:
      "Organisations that need to understand and continuously monitor their external exposure — particularly those in regulated sectors where supply chain risk, brand protection and third-party compromise are material concerns. Also appropriate as the first intelligence layer for organisations embarking on a managed detection or offensive security programme.",
    whatWeDo: [
      "Continuous domain and subdomain footprint monitoring via DomainTools Iris Investigate",
      "Leaked credential monitoring across breach databases and dark web sources",
      "Brand and lookalike domain detection to surface phishing infrastructure",
      "Infrastructure change alerting for DNS, WHOIS and certificate transparency records",
      "Threat actor profiling and sector-specific intelligence relevant to your industry",
      "Supply chain and third-party domain risk scoring",
      "Monthly domain intelligence report with analyst commentary",
      "Integration with existing SIEM, SOAR or managed detection service",
    ],
    howWeDeliver: [
      "Week 1: Domain asset inventory — we map your registered domains, subdomains and associated infrastructure",
      "Week 2: Baseline intelligence report — initial exposure findings with risk-rated recommendations",
      "Month 1 onwards: Continuous alerting with analyst triage and monthly written briefing",
      "Quarterly: Intelligence review — trends, threat actor activity and recommended posture changes",
      "On-demand: Targeted investigation for incidents, M&A due diligence or regulatory requirements",
    ],
    caseStudy: {
      result:
        "A UK professional services firm discovered 14 lookalike domains registered against their brand within 48 hours of onboarding. Three were actively being used in phishing campaigns targeting their clients. All were taken down within 72 hours using our incident response support.",
      org: "UK Professional Services Firm",
    },
    category: "Detection & Intelligence",
    complianceRelevance: ["ISO 27001", "DORA", "FCA", "NIS2", "UK GDPR"],
    relatedServices: ["assessment", "managed-detection", "offensive-security"],
    badge: "Powered by DomainTools",
  },
  "swift-assurance": {
    title: "SWIFT & Payments Assurance",
    tagline: "SWIFT CSP readiness, gap analysis and attestation support for payment infrastructure.",
    heroDesc:
      "Infosec K2K's SWIFT & Payments Assurance practice helps banks, payment processors and correspondent banking organisations meet their SWIFT Customer Security Programme (CSP) obligations — and go beyond compliance to build a genuinely secure payments infrastructure.",
    icon: "CreditCard",
    targetClient:
      "Banks, building societies, payment processors and any organisation connected to the SWIFT network that needs to demonstrate CSP compliance, prepare for annual attestation or respond to SWIFT-mandated control improvements. Also relevant to organisations undergoing DORA or PCI DSS assessments where payment rail security overlaps.",
    whatWeDo: [
      "SWIFT CSP mandatory and advisory control gap assessment against the current CSCF version",
      "Evidence collection planning and control owner assignment",
      "Remediation prioritisation with risk-rated findings and implementation guidance",
      "Attestation support including KYC-SA submission preparation and reviewer liaison",
      "Integration of CSP findings with broader ISO 27001 or DORA compliance programmes",
      "Secure architecture review of SWIFT-connected infrastructure including jump servers and HSMs",
      "Annual attestation readiness review and change delta analysis for updated CSCF versions",
      "Training and awareness for payment operations and IT security teams",
    ],
    howWeDeliver: [
      "Week 1–2: Scoping and evidence inventory — SWIFT connectivity architecture review and control owner mapping",
      "Week 2–4: Gap assessment — structured walkthrough of mandatory and advisory controls with evidence scoring",
      "Week 4–6: Report delivery — risk-rated gap register, remediation roadmap and attestation readiness rating",
      "Ongoing: Remediation support, evidence tracker management and annual attestation preparation",
    ],
    caseStudy: {
      result:
        "A Tier 2 UK bank achieved SWIFT CSP attestation with zero mandatory control failures for the first time in three years. The programme also identified eight advisory control gaps that were incorporated into the following year's security budget.",
      org: "Tier 2 UK Bank",
    },
    category: "Assurance",
    complianceRelevance: ["SWIFT CSP", "PCI DSS", "DORA", "FCA", "ISO 27001"],
    relatedServices: ["assessment", "assurance", "managed"],
    badge: "Regulated",
  },
  "technical-resources": {
    title: "Technical Resource Delivery",
    tagline: "Flexible, governed security resource — UK, Germany and India — across every domain we operate in.",
    heroDesc:
      "Infosec K2K's Technical Resource Delivery capability gives organisations direct access to experienced security professionals on the engagement model that suits them — project-based, dedicated placement, managed service augmentation, or on-demand advisory. Every resource is governed through UK or Germany/EU frameworks with full time tracking, customer dashboard visibility and back-end integration into Zoho Projects and Zoho People.",
    icon: "Users2",
    targetClient:
      "Organisations that have a defined security programme but lack the in-house headcount to deliver it — or that need to rapidly augment an existing team with domain-specific expertise. Also appropriate for firms undergoing DORA, NIS2 or ISO 27001 programmes where interim security resource is required under a governed contract, and for multi-jurisdiction programmes needing coordinated UK, EU and India delivery.",
    whatWeDo: [
      "Project-based resource: named consultants scoped and delivered against a fixed Statement of Work, with defined milestones and a client portal for full delivery transparency",
      "Dedicated resource placement: experienced K2K professionals embedded in your team for a defined period — daily-rate or monthly retainer, governed by UK or Germany/EU contract frameworks",
      "Managed service augmentation: extend an existing K2K managed service (IAM, detection, assurance) with additional resource headcount during programme peaks or compliance cycles",
      "On-demand advisory: flexible access to senior specialists — IAM architects, PAM engineers, SOC analysts, assurance leads — drawn down by the day or week without a long-term commitment",
      "Cross-domain coverage: resource available across identity and IAM/PAM, managed detection and SOC, domain intelligence, security assurance and compliance, and offensive security",
      "Multi-geography delivery: UK-based consultants for on-site and regulated-entity requirements; Germany/EU resources for DORA, NIS2 and EU-regulated engagements; India-based resources for continuous monitoring, extended-hours coverage and cost-efficient programme delivery",
      "Full time tracking and governance: every resource logs time against Zoho Projects tasks, reviewed weekly by a dedicated K2K engagement manager, with utilisation and burn-rate visible in the client portal",
      "Governance and compliance: all engagements governed by a Master Services Agreement with jurisdiction-specific supplementary terms (UK standard or Germany/EU GDPR-aligned); IR35 and right-to-work compliance handled by K2K for all UK placements",
      "Onboarding and offboarding management: K2K manages security clearance documentation, NDA and BAA execution, equipment provisioning coordination and knowledge transfer at engagement close",
      "Quarterly resource reviews: formal check-in between K2K engagement manager, resource lead and client sponsor to review utilisation, quality, domain coverage and forward planning",
    ],
    howWeDeliver: [
      "Step 1 — Requirements and scoping (Week 1): Structured session to establish domain, geography, seniority, engagement model, governance framework and IR35 status. Output: Resource Brief and commercial proposal within 5 business days.",
      "Step 2 — Resource matching and SOW (Week 1–2): K2K matches requirements against internal bench and partner network. Named CVs presented for client approval. Statement of Work or Call-Off Order executed.",
      "Step 3 — Onboarding and access (Week 2–3): Resource onboarding — security documentation, system access, client induction, project context handover. Resources added to Zoho Projects with task assignments.",
      "Step 4 — Delivery and time governance (Ongoing): Resources deliver against agreed scope. Time logged daily in Zoho People, reviewed weekly by K2K engagement manager, surfaced in portal Timesheets and Utilisation tabs. Monthly burn-rate report issued.",
      "Step 5 — Review, renewal and close (Quarterly): Quarterly resource review with client sponsor. At close: formal knowledge transfer document, access offboarding, final utilisation and delivery summary.",
    ],
    caseStudy: {
      result:
        "A UK-regulated financial services group undergoing a DORA-mandated IAM programme engaged K2K for three dedicated resources — a PAM architect (UK), an IGA engineer (India) and a compliance analyst (UK) — across six months. The programme delivered on schedule with 100% time accountability through the portal, and the engagement was extended by four months for the DORA attestation phase.",
      org: "UK-Regulated Financial Services Group",
    },
    category: "Delivery",
    complianceRelevance: ["DORA", "NIS2", "ISO 27001", "FCA", "UK GDPR", "GDPR (Germany/EU)", "IR35"],
    relatedServices: ["managed", "implementation", "assurance", "offensive-security"],
    badge: "Multi-Jurisdiction",
  },
};
